Test branch
artur-faizov/TestTask_1_web_server pull request #1
Opened 2021-04-26 19:06 UTC by artur-faizov

My Test Pull Request

2021-04-28 17:14 UTC, ahamtat requested changes

2021-04-28 17:14 UTC, ahamtat commented on main.go
> +	HttpStatus    string
Здесь хотелось бы видеть целочисленный статус код: https://golang.org/src/net/http/status.go
Его всегда можно преобразовать в строку функцией StatusText(code int) string

2021-04-28 17:14 UTC, ahamtat commented on main.go
>  			delete(History, deleteIdInt32)
В имени переменной обычно не указывают тип. При преобразовании типов можно не создавать новую переменную:
`
delete(History, int32(id))
`

2021-04-28 17:14 UTC, ahamtat commented on main.go
> +			case "HEAD":
Этот метод не нужно обрабатывать

2021-04-28 17:14 UTC, ahamtat commented on main.go
> +			body, err := ioutil.ReadAll(resp.Body)
Если в switch выполнится ветка default, то resp будет не определен. При разименовании resp.Body выскочит паника

2021-04-28 17:14 UTC, ahamtat commented on main.go
>  			var IndexElem HistoryIndexElement
Вот здесь тоже нужно объявление через инициализацию как для historyElement выше

2021-04-28 17:14 UTC, ahamtat commented on main.go
>  			HistoryIndex = append(HistoryIndex, IndexElem)
Вообще, это все можно написать совсем по-гошному:
`HistoryIndex = append(HistoryIndex, HistoryIndexElement{ID: x,Time: time.Now().Format("2006-01-02 15:04:05.000")})`

2021-04-28 17:14 UTC, ahamtat commented on main.go
> +				http.Error(w, err.Error(), http.StatusBadRequest)
Тут статус ошибки нужен не StatusBadRequest. Нужно вернуть 500-ую - Internal Server Error

2021-04-28 17:39 UTC, ahamtat requested changes

2021-04-28 17:39 UTC, ahamtat commented on main.go
> +	Status string // tag if removed from history
Тут статус тоже лучше сделать целочисленным

2021-04-28 17:39 UTC, ahamtat commented on main.go
>  }
Что делает эта функция?

2021-04-28 17:39 UTC, ahamtat commented on main.go
> +			deleteIdInt64, err := strconv.ParseInt(deleteIdString, 10, 32)
Здесь от типов в именах переменных тоже надо избавиться.

2021-04-28 17:39 UTC, ahamtat commented on main.go
> +			var resp *http.Response
Меня смущает resp, объявленный снаружи switch, когда его инициализация происходит внутри. Лучше затащить его внутрь каждого case.

2021-04-28 17:39 UTC, ahamtat commented on main.go
> +				resp, err = http.Get(reqParams.Url)
Тогда и объявление ошибки станет излишним. Можно будет просто:
`resp, err := http.Get(reqParams.Url)`

2021-04-28 17:39 UTC, ahamtat commented on main.go
> +				defer resp.Body.Close()
И defer тоже будет работать правильно

2021-04-28 17:39 UTC, ahamtat commented on main.go
> +				historyRange = append(historyRange, element)
Здесь написать крутое добавление элемента)) см. выше

2021-04-28 17:39 UTC, ahamtat commented on main.go
> +				historyRange = append(historyRange, element)
Здесь тоже

2021-04-28 17:39 UTC, ahamtat commented on main.go
> +		w.WriteHeader(http.StatusCreated)
http.StatusCreated может быть возвращен только для метода POST. Какой метод ты здесь обрабатываешь?

2021-04-29 03:31 UTC, artur-faizov commented on main.go
> +	HttpStatus    string
Fixed

2021-04-29 03:36 UTC, artur-faizov commented on main.go
>  			delete(History, deleteIdInt32)
Запомню! исправил

2021-04-29 03:36 UTC, artur-faizov commented on main.go
> +			case "HEAD":
удалил

2021-04-29 03:45 UTC, artur-faizov commented on main.go
> +			body, err := ioutil.ReadAll(resp.Body)
Не совсем понимаю суть проблемы.
Дефолтный сценарий вот такой:
`default:
				_,err = w.Write([]byte("unknown request type"))
				if err != nil {
					log.Println(err)
				}
				return
			}`
в конце идет return который как мне кажется завешает всю гоурутину
я потестировал дефолтный сценарий, паника вроде бы не возникает. Я может как то не так ее ожидаю увидеть и она гдето под капотом случается.

2021-04-29 03:55 UTC, artur-faizov commented on main.go
>  			var IndexElem HistoryIndexElement
Исправил, кажется уже второй раз на эти грабли наступаю. Постараюсь не повторять

2021-04-29 04:01 UTC, artur-faizov commented on main.go
>  			HistoryIndex = append(HistoryIndex, IndexElem)
Спасибо за пример. Запомню подход минимализма. На мой нубский взгляд страдает прозрачность. Думаю со временем пройдет )

2021-04-29 04:29 UTC, artur-faizov commented on main.go
> +			body, err := ioutil.ReadAll(resp.Body)
позднее дефолтный сценарий стал еще короче 
  `default:
			http.Error(w, "HTTP method not in list of supported: DELETE , POST", http.StatusBadRequest)
			return
		}`

2021-04-29 04:31 UTC, artur-faizov commented on main.go
> +				http.Error(w, err.Error(), http.StatusBadRequest)
переделал. Вообще как то не задумывался о том что я там возвращаю. ошибка и ошибка ) был невнимателен - поправил

2021-04-29 04:32 UTC, artur-faizov commented on main.go
> +	Status string // tag if removed from history
целочисленным сделать его конечно можно. Но где хранить значения целочисленных статус кодов?
Это же не стандартные коды а мой статус того удалено значение из базы или нет. Сейчас я записываю туда время удаления из базы

2021-04-29 04:59 UTC, artur-faizov commented on main.go
> +	Status string // tag if removed from history
В общем сделал целочисленным. Единственный статус 1 - значит элемент удален из истории

2021-04-29 05:01 UTC, artur-faizov commented on main.go
>  }
сохранил ее себе в закомментированном виде. Функция должна была удалять элемент слайса из индекса при удалении элемента по запросу. Но потом подумал что для постраничного вывода лучше будет индекс не трогать чтобы элементы не сдвигались и отказался от удаления элемента из индекса вообще. Отсюда появился статус в индексе о том что элемент удален
Если кратко то сейчас функция не используема и ничего не делает. Удалю ее из кода тогда

2021-04-29 05:09 UTC, artur-faizov commented on main.go
> +			deleteIdInt64, err := strconv.ParseInt(deleteIdString, 10, 32)
сделал.

2021-04-29 05:12 UTC, artur-faizov commented on main.go
> +			var resp *http.Response
да я как раз и не зотел плодить дублирующий код внутри каждого case. Как то дублирование кода противоречит духу программирования. Вроде работает все. Может лучше проверим места которые смущают, подскажи что может пойти не так, я потестирую

2021-04-29 05:15 UTC, artur-faizov commented on main.go
> +				historyRange = append(historyRange, element)
к моменту когда я дошел до этого замечания я это место уже поправил. Кажется я теперь никогда не забуду как сразу элемент добавлять вместе с инициализацией ))

2021-04-29 05:15 UTC, artur-faizov commented on main.go
> +				historyRange = append(historyRange, element)
и тут поправил

2021-04-29 05:19 UTC, artur-faizov commented on main.go
> +		w.WriteHeader(http.StatusCreated)
это я бездумно накопипастил из интернета когда пытался вывести json красиво в браузере.
сейчас просто удалил эти две строки

2021-04-29 16:10 UTC, merged

2021-05-06 04:43 UTC, ahamtat commented on main.go
> +			body, err := ioutil.ReadAll(resp.Body)
Дефолтный сценарий не присваевает переменную resp. Поэтому в body, err := ioutil.ReadAll(resp.Body) ниже может выскочить паника.

2021-05-06 04:46 UTC, ahamtat commented on main.go
> +	Status string // tag if removed from history
> Но где хранить смысловую транскрипцию значения целочисленных статус кодов?

Транскрипция есть в https://golang.org/src/net/http/status.go

2021-05-06 04:50 UTC, ahamtat commented on main.go
> +			var resp *http.Response
Смущает, что при объявлении эта переменная = nil. А что будет, если ты неправильно ее присвоишь? Паника конечно.

> Вроде работает все.
При разработке все работает. Когда выкатываешь на прод, проявляются условия, которые не существовали при разработке, и код начинает вести себя непредсказуемо.