Update main.go
artur-faizov/TestTask_1_web_server pull request #4
Opened 2021-04-30 02:52 UTC by artur-faizov

New history method without index

2021-05-02 08:06 UTC, ahamtat requested changes
Хорошая работа. Надеюсь, ты тоже можешь видеть как улучшилось качество кода без лишнего слайса. Сделай, пожалуйста, исправления по моим комментариям.

2021-05-02 08:06 UTC, ahamtat commented on main.go
> +		historyCopy := make([]historyCopyElement, 0)
Как можно оптимизировать это выделение памяти, чтобы в дальнейшем избежать переаллокаций слайса?

2021-05-02 08:06 UTC, ahamtat commented on main.go
> +		mux.Lock()
Можно сделать Read Lock - побыстрее будет работать ))

2021-05-02 08:06 UTC, ahamtat commented on main.go
> +			historyCopy = append(historyCopy, historyCopyElement{ID: key, Element: element})
Как здесь можно оптимизировать копирование по памяти и быстродействию?

2021-05-02 08:06 UTC, ahamtat commented on main.go
> +		}
Молодец, что сделал свою реализацию пузырька. Попробуй сделать сортировку через интерфейс https://golang.org/pkg/sort/#Interface

2021-05-02 08:06 UTC, ahamtat commented on main.go
>  		}
Как сделать новый слайс средствами языка без аллокации и копирования?

2021-05-03 00:09 UTC, artur-faizov commented on main.go
> +		historyCopy := make([]historyCopyElement, 0)
Сделать его глобальным? Тогда при каждом запросе хистори мы будем перезаполнять тот же самый слайс. Верно? Единственное придется сделать мьютекс на него чтобы не было конфликтов с двумя хистори запросами. Но так как запросы хистори у нас редкие думаю мы можем на это пойти. Зато память всегда будет занята не больше одного слайса.
Я правильно рассуждаю? Или имелось ввиду что-то другое?

Скажи пожалуйста если бы одновременно мог выполняться только один запрос хистори. по каким то сторонним причинам, то чем в таком случае плохо переаллоцирование памяти? Увеличивает фрагментированности памяти? Или во время переаллоцирования оно как бы используется в двойном объеме ? или нагрузка на ЦПУ и шину памяти? Или все вместе? Просто для моего понимания что самое критичное о чем мы думаем во время программирования?

2021-05-03 00:15 UTC, artur-faizov commented on main.go
> +		mux.Lock()
Точно нам же важно только чтобы никто не записал в History что-то во время вычитывания, а вот пусть вычитывают другие на нас в данном месте не повлияет

2021-05-03 01:05 UTC, artur-faizov commented on main.go
> +			historyCopy = append(historyCopy, historyCopyElement{ID: key, Element: element})
подозреваю что будет быстрее и меньше по памяти если я сделаю Range только по индексу без Element 
Нашел в интернете про пакет testing.  Хочу разобраться и применить его для сравнения производительности

2021-05-03 14:54 UTC, artur-faizov commented on main.go
> +		historyCopy := make([]historyCopyElement, 0)
Я подумал что возможно имелось ввиду создавать слайс сразу размером в размер мапы а не нулевого размера.

2021-05-06 04:57 UTC, ahamtat commented on main.go
> +		historyCopy := make([]historyCopyElement, 0)
Не, все гораздо проще.Нужно пользоваться указателями. Тогда при копировании элементов слайса не будут копироваться значения полей структур, а просто скопируются указатели на структуры. Это гораздо быстрее и сборщику мусора потом меньше работы.

> чем в таком случае плохо переаллоцирование памяти?
Создается ненужная нагрузка на процессор и шину данных.

2021-05-06 04:57 UTC, ahamtat commented on main.go
> +			historyCopy = append(historyCopy, historyCopyElement{ID: key, Element: element})
Копировать по указателю, а не по значению.

2021-05-09 17:59 UTC, artur-faizov commented on main.go
> +		historyCopy := make([]historyCopyElement, 0)
переделал в слайс указателей

2021-05-09 18:00 UTC, artur-faizov commented on main.go
> +			historyCopy = append(historyCopy, historyCopyElement{ID: key, Element: element})
переделал в слайс указателей и оперирую указателями

2021-05-09 18:01 UTC, artur-faizov commented on main.go
>  		}
так как весь слайс нам не нужен и используем мы его по сути один раз, то я просто заменил содержание того же слайса выкинув ненужные данные
historyCopy = historyCopy[offset:limit]

2021-05-09 18:32 UTC, artur-faizov commented on main.go
> +		}
переделал

2021-05-10 16:46 UTC, ahamtat approved these changes

2021-05-10 16:46 UTC, ahamtat commented
Заапрувил! Можно мерджить!

2021-05-15 23:47 UTC, merged