Update main.go
artur-faizov/TestTask_1_web_server pull request #5
Opened 2021-04-30 17:30 UTC by artur-faizov

Implemented support for POST method request

2021-05-02 08:23 UTC, ahamtat requested changes
Прошу поправить код по моим комментариям

2021-05-02 08:23 UTC, ahamtat commented on main.go
> +	Header map[string]string `json:"header"`
Там немного другой тип: map[string][]string https://golang.org/pkg/net/http/#Header

2021-05-02 08:23 UTC, ahamtat commented on main.go
> +					return
У запроса может не быть заголовков, поэтому здесь не надо ошибку возвращать

2021-05-02 08:23 UTC, ahamtat commented on main.go
> +					http.Error(w, err.Error(), http.StatusInternalServerError)
Здесь ошибка связана не с внутренней логикой сервера, а с вызовом в сторонний сервис. Поэтому надо возвращать 502-ую или 503-ю https://golang.org/src/net/http/status.go

2021-05-02 08:23 UTC, ahamtat commented on main.go
> +			defer func() {
Вроде в 129-ой строке уже есть defer?

2021-05-09 20:32 UTC, artur-faizov commented on main.go
> +	Header map[string]string `json:"header"`
поправил

2021-05-09 20:33 UTC, artur-faizov commented on main.go
> +					return
а это я где-то прочитал что не может быть без заголовков POST запросов
убрал

2021-05-09 20:41 UTC, artur-faizov commented on main.go
> +					http.Error(w, err.Error(), http.StatusInternalServerError)
исправил.
Вопрос: почему когда делаем Get то при получении ошибки пишем BadRequest
А в данном случае с POST возвращаем 502 или 503 ?

2021-05-09 21:24 UTC, artur-faizov commented on main.go
> +			defer func() {
Посмотрел, удалил defer из каждой ветки switch case:
case Get: line 92
case Post: line 125
Чтобы было только в одном месте

2021-05-10 16:37 UTC, ahamtat commented on main.go
> +					http.Error(w, err.Error(), http.StatusInternalServerError)
Потому что ошибка связана с вызовом в сторонний сервис

2021-05-10 16:48 UTC, ahamtat approved these changes
Заапрувил! Можно мерджить!

2021-05-15 23:45 UTC, merged