Conceptual try
artur-faizov/TestTask_1_web_server pull request #6
Opened 2021-05-17 15:08 UTC by artur-faizov

Conceptual try
Тут только попробовал саму технолошию запуска Юнит тестов

2021-05-18 06:03 UTC, ahamtat requested changes
Нужно еще поизучать теорию про юнит-тестирование HTTP серверов. Ссылки на статьи вышлю отдельно.

2021-05-25 06:50 UTC, ahamtat requested changes
Надо поделать примеры из статей про МОКи и сделать по аналогии

2021-05-25 06:50 UTC, ahamtat commented on main.go
> +func handlers(myDB_ *myDB) http.Handler {
Подчеркивание в имени переменной - это не Го-стиль. Лучше просто myDB или совсем хорошо db.

2021-05-25 06:50 UTC, ahamtat commented on main.go
> +		myDB_.mux.RLock()
Здесь идет обращение к неэкспортируемому члену структуры. По идее компилятор должен ругаться.
Мьютекс скрыт внутри структуры - это хорошо. Надо подумать как лочить его внутри, а не снаружи. Подсказка - добавить к структуре функции доступа и модификации.

2021-05-25 06:50 UTC, ahamtat commented on main.go
> +	myDB_ := myDB{
Большие структуры лучше инициализировать по указателю, чтобы избежать копирования.

2021-05-25 06:50 UTC, ahamtat commented on main_test.go
>  	bodyContent := "{\"method\": \"GET\", \"url\": \"http://google.com\"}"
Форматирование можно сделать более удобочитаемым, если использовать апострофы:
https://play.golang.org/p/6Ix4Hvs_SYT

2021-05-31 16:04 UTC, artur-faizov commented on main.go
> +		myDB_.mux.RLock()
Почитал, похоже у меня компилиться потому что весь код внутри одного модуля. Если бы main был отдельно то не скомелировалось бы. Спасибо за подсказку про методы. Сейчас буду реализовывать.

2021-06-01 17:25 UTC, ahamtat requested changes
С применением интерфейса и его реализации хорошо получилось. Код стал гораздо понятней. Пожалуйста, сделай исправления по моим комментариям.

2021-06-01 17:25 UTC, ahamtat commented on main.go
>  				}
В предыдущих 4-х строках не совсем понимаю, что происходит? Можешь пояснить?

2021-06-01 17:25 UTC, ahamtat commented on main.go
>  		}
Ты хочешь залогировать ошибку? Можно проще:
`log.Println(err)`

2021-06-01 17:25 UTC, ahamtat commented on main.go
> +		lastID:  &id,
Вот тут, как раз, можно по значению))) Айдишники разрешено копировать без проблем)

2021-06-01 17:25 UTC, ahamtat commented on main.go
> +type myDB struct {
Реализацию интерфейса тоже неплохо бы вынести в отдельный файл и написать к нему юнит-тест.

2021-06-02 16:56 UTC, artur-faizov commented on main.go
>  				}
если я правильно понимаю на что ссылается твой комментарий (кажется вот на это resJsonNice, err := json.MarshalIndent(res, "", "\t"))
то я ответ от стороннего сервиса из формата джысон преобразую в красивый форматированный текст чтобы вывести ответ сразу клиенту который отправил запрос. Так я сразу вижу как выполнился мой запрос что я отправил моему сервису.
Если преобразование зафейлилось то пишу что ошибка

2021-06-02 17:00 UTC, artur-faizov commented on main.go
>  		}
В коде вроде так и написано. или опять я куда-то не туда смотрю. Подскажи пожалуйста какая строчка кода?

2021-06-02 17:03 UTC, artur-faizov commented on main.go
> +		lastID:  &id,
Понимаешь какая штука. когда там по значению то не работает программа: значений айди всегда оказывается 0. И каждый запрос добавляется в базу по одному и тому же айди

Кстати вот тот пример когда и создать переменную сразу ссылающуюуся на адрес в памяти не получилось:
lastID:  &int32(0) не прокатило, пришлось сначала создать переменную а потом уже сослаться на ее адрес в памяти. Помнишь мы обсуждали что можно сразу ссылаться на результат без создания сущности

2021-06-02 17:04 UTC, artur-faizov commented on main.go
> +type myDB struct {
Черт забыл, ты же говорил мне это с самого начала. Щас вынес и напишу тесты, поправка, попробую написать ))

2021-06-03 06:39 UTC, ahamtat requested changes
Юнит-тесты лучше разнести по нескольким функциям: TestAdd(), TestDelete(), TestGetHistory(). Ошибки нужно обрабатывать через require или assert

2021-06-03 06:39 UTC, ahamtat commented on Database_test.go
> +	testDB := &myDB{
Для инициализации структуры можно сделать конструктор в database.go:
`
func NewDB() *DB {
  return &DB{ ... }
}
`

2021-06-03 06:39 UTC, ahamtat commented on Database.go
> +type myDB struct {
Будет более информативно назвать структуру MemoryDB или MapDB например

2021-06-03 06:39 UTC, ahamtat commented on Database_test.go
> +		HttpStatusCode: 100,
Для статускодов лучше использовать константы из https://golang.org/src/net/http/status.go

2021-06-03 06:39 UTC, ahamtat commented on Database_test.go
> +		if err != nil {
В юнит-тестах проверка ошибок делается средствами пакетов require или assert, т.е. в этом случае:
`require.Nil(t, err)`
https://pkg.go.dev/github.com/stretchr/testify/require#Nil

или, что то же самое:
`assert.NotNil(t, err)`
https://pkg.go.dev/github.com/stretchr/testify/assert#NotNil

2021-06-03 06:39 UTC, ahamtat commented on Database_test.go
> +		}
`require.Len(t, testDB.History, 1)`

2021-06-03 06:39 UTC, ahamtat commented on Database_test.go
> +			}
`require.Equal(t, 100, testDB.History[key].Respond.HttpStatusCode)`

2021-06-03 06:39 UTC, ahamtat commented on main.go
> +		lastID:  &id,
> И каждый запрос добавляется в базу по одному и тому же айди
Этого не может быть, т.к. в функции Add инкрементируется lastID. Давай тогда в юнит-тест добавим проверку на это.

2021-06-05 18:48 UTC, artur-faizov commented on main.go
> +		lastID:  &id,
Уран нашел ошибку, в методы структуры я передавал не ссылку на структуру а копию структуры
Было например так
func (db myDB) Add(newHistoryElement HistoryElement) error {
А надо было так
func (db *myDB) Add(newHistoryElement HistoryElement) error {
Еще тогда меня терзали сомнения по отсутствию ссылки, но так как оно заработало и без этого то я пропустил этот момент

В общем сейчас я переделал ID на просто элемент структуры без ссылки на значение
Unit тесты покрывают проверку ID

2021-06-05 18:57 UTC, artur-faizov commented on Database.go
> +type myDB struct {
Принято

2021-06-05 18:57 UTC, artur-faizov commented on Database_test.go
> +	testDB := &myDB{
Да так удобнее!

2021-06-07 17:21 UTC, ahamtat approved these changes
Юнит-тесты отличные! Поправь, пожалуйста, маленькие ошибочки и можно мерджить.

2021-06-07 17:21 UTC, ahamtat commented on Database_test.go
> +		}
Так, в принципе, тоже можно, но хорошим стилем было бы:
`
for _, value := range testDB.History {
			require.Equal(t, http.StatusOK, value.Respond.HttpStatusCode, "Data is corrupted in DB")
		}`

2021-06-07 17:21 UTC, ahamtat commented on Database_test.go
> +	t.Run("Test: Adding multiple elements to DB", func(t *testing.T) {
Функции Test... можно смело разбить еще на более мелкие по t.Run ))

2021-06-07 17:21 UTC, ahamtat commented on Database_test.go
> +		require.Len(t, testDB.History, N+1, "incorrect size of DB with 3 lements. Expected: 3, in facet size is: %d", len(testDB.History))
А почему 3, 101 далматинца же добавляем?)

2021-06-07 17:21 UTC, ahamtat commented on main.go
> +					http.Error(w, "No BODY specified for request", http.StatusBadRequest)
Все-таки лучше вернуть клиенту ошибку от стороннего сервиса, а не замещать ее

2021-06-07 21:46 UTC, artur-faizov commented on Database_test.go
> +		}
а я почему то думал что наоборот лучше чем копировать элемент, лучше сослаться на него прямо в срезе
переделал в общем как надо

2021-06-07 21:50 UTC, artur-faizov commented on Database_test.go
> +		require.Len(t, testDB.History, N+1, "incorrect size of DB with 3 lements. Expected: 3, in facet size is: %d", len(testDB.History))
а черт забыл. у меня сначала было всего 3 элемента. потом я подумал что на трех элементах и с ошибкой в коде может пройти тест. Убрал фикс из оповещения. вставил туда переменную.

2021-06-07 21:58 UTC, artur-faizov commented on main.go
> +					http.Error(w, "No BODY specified for request", http.StatusBadRequest)
Это я видимо случайно закопипастил не туда. Там двумя строчками выше точно такая же ошибка.
Убрал, спасибо.

2021-06-07 22:05 UTC, artur-faizov commented on Database_test.go
> +	t.Run("Test: Adding multiple elements to DB", func(t *testing.T) {
Доразбил только для проверки получения истории. В остальных там итак вроде минимальные по логике группировки тестов

2021-06-08 15:27 UTC, merged