PG database implemented
artur-faizov/TestTask_1_web_server pull request #7
Opened 2021-06-14 17:08 UTC by artur-faizov

Implementation of Postgres DB

2021-06-15 18:14 UTC, ahamtat requested changes
Хорошо, но можно лучше)) Пожалуйста, сделай исправления по моим комментариям.

2021-06-15 18:14 UTC, ahamtat commented on DatabasePG.go
> +func DbPgConnect() (*sql.DB, error) {
Конструкторы объектов обычно именуются с New... - так их распознают в тексте программы:
```
func NewDBPG(connString string) *PgDB {
...
}
```

Но, круче всего из конструктора возвращать интерфейс для работы с БД.

2021-06-15 18:14 UTC, ahamtat commented on DatabasePG.go
> +func GetLastID(db *sql.DB) (int32, error) {
Эту функцию можно привязать к структуре и сделать реализацией интерфейса

2021-06-15 18:14 UTC, ahamtat commented on DatabasePG.go
> +}
Это можно поместить в конструктор объекта

2021-06-15 18:14 UTC, ahamtat commented on DatabasePG.go
> +	mux      *sync.RWMutex
Для постгреса мьютекс не нужен, т.к. он сам синхронизирует запросы. Для высоконагруженных приложений применяют транзакции к БД.

2021-06-15 18:14 UTC, ahamtat commented on DatabasePG.go
> +		INSERT INTO "TestTable" (ID, method , url, body, time, "respStatus", length)
У таблиц обычно делают свой индекс с автоинкрементом

2021-06-15 18:14 UTC, ahamtat commented on DatabasePG.go
> +func addHeaders(db *sql.DB, tableName string, id int32, headers *map[string][]string) error {
Мапу можно передавать по значению, т.к. внутри у нее есть указатель на бакеты с данными.

2021-06-15 18:14 UTC, ahamtat commented on DatabasePG.go
> +		panic(err)
Лучше вернуть ошибку. Паниковать в программе можно только в самых крайних случаях. Лучше вообще не паниковать))

2021-06-15 18:14 UTC, ahamtat commented on DatabasePG.go
> +	}
Можно объединить данные из нескольких таблиц с помощью JOIN

2021-06-16 15:33 UTC, artur-faizov commented on DatabasePG.go
> +func GetLastID(db *sql.DB) (int32, error) {
она используется для инициализации самой структуры, без нее я не могу инициализировать структуру с правильным ID последнего элемента. это как курица и яйцо.
Если надо я могу сделать отдельный метод на получение последнего ID хотя нам вроде не требуется получать ID  последнего элемента

2021-06-18 00:10 UTC, artur-faizov commented on DatabasePG.go
> +func DbPgConnect() (*sql.DB, error) {
обсудили этот момент

2021-06-18 00:11 UTC, artur-faizov commented on DatabasePG.go
> +func GetLastID(db *sql.DB) (int32, error) {
ушли от передачи ID  внутрь структуры. Теперь за ID элементов следит Постгрес

2021-06-18 00:12 UTC, artur-faizov commented on DatabasePG.go
> +	mux      *sync.RWMutex
удалил Мьютекс

2021-06-18 00:12 UTC, artur-faizov commented on DatabasePG.go
> +		INSERT INTO "TestTable" (ID, method , url, body, time, "respStatus", length)
сделал свой индекс с автоинкрементом и он же является ID запроса

2021-06-18 00:34 UTC, artur-faizov commented on DatabasePG.go
> +func addHeaders(db *sql.DB, tableName string, id int32, headers *map[string][]string) error {
спасибо за напоминание. Перечитал еще раз статью про устройство мапы

2021-06-18 00:34 UTC, artur-faizov commented on DatabasePG.go
> +		panic(err)
это да!

2021-06-19 02:57 UTC, artur-faizov commented on DatabasePG.go
> +	}
я сделал через JOIN но работать с джойниной таблицей получился такой геморой что я бы предпочел в данном конкретном случае так не делать.
Старый метод я оставил большим закоментированным куском

2021-06-20 10:26 UTC, ahamtat requested changes
Сорри, запутался в твоем коде. Давай расчищать.
Сделай, пожалуйста, ПР в котором будет:
1. Вставка записи только в таблицу TestTable
2. Комментарии, поясняющие участки кода, разбитые по логическим блокам

и не будет:
1. Закомментированных участков кода
2. Работы с таблицами Request/Respond Headers - потом добавим.

2021-06-20 10:26 UTC, ahamtat commented on DatabasePG.go
> +	rows, err := db.Query(`SELECT nextval('"TestTable_id_seq"')`)
Вот это для чего нужно?

2021-06-20 23:12 UTC, artur-faizov commented on DatabasePG.go
> +	rows, err := db.Query(`SELECT nextval('"TestTable_id_seq"')`)
это я спрашиваю какой будет следующий номер в таблице и добавляю элемент в тиблицу? если добавилось успешно то с таким же ID добавляю элементы в Header таблицы, а если не успешно (ктото успел уже записать туда данные) то запрашиваю в рекурсии следующий номер и снова пытаюсь записать (там стоял лимит на 100 попыток).
Так как мы пока делаем только с одной таблицей то это все не надо и я это выкинул

2021-07-28 16:43 UTC, merged