Postgres db interface basic
artur-faizov/TestTask_1_web_server pull request #8
Opened 2021-06-20 23:22 UTC by artur-faizov

Only TestTable with main data (no headers)

2021-06-26 16:31 UTC, ahamtat requested changes
Хорошо. Попробуй сделать так, чтобы SQL-запросы избавили тебя от избыточной работы в коде программы.

2021-06-26 16:31 UTC, ahamtat commented on DatabasePG.go
>  	}
Смысл этого задания в том, чтобы по-максимому использовать возможности SQL. В том числе ограниченную выборку из БД со смещением.

2021-06-26 16:31 UTC, ahamtat commented on DatabasePG.go
> +		err = requests.Scan(&id, &url, &method, &body, &requestTime, &respStatus, &length)
Предлагаю создать структуру с тегами db и сканировать в структуру, чем в переменные по-отдельности

2021-06-26 16:31 UTC, ahamtat commented on DatabasePG.go
> +		historyCopyElement := historyCopyElement{
Называть переменную именем типа - плохая практика. Запутывает.

2021-06-26 16:31 UTC, ahamtat commented on DatabasePG.go
> +		historyCopy = append(historyCopy, &historyCopyElement)
Можно создать переменную по указателю. И в аппенде добавлять указатель.

2021-06-26 16:31 UTC, ahamtat commented on DatabasePG.go
>  	sort.Sort(ByTime(historyCopy))
Сортировку тоже можно сделать в SQL

2021-06-27 19:10 UTC, artur-faizov commented on DatabasePG.go
> +		historyCopy = append(historyCopy, &historyCopyElement)
Переделал. Я так понимаю выигрыш в том что мы сразу получаем только указатель и добавляем только его вместо того чтобы создавать копию и давать ссылку на копию как дела я. Я это правильно понял?

2021-06-27 19:11 UTC, artur-faizov commented on DatabasePG.go
>  	sort.Sort(ByTime(historyCopy))
да так в 100 раз удобнее

2021-06-27 19:11 UTC, artur-faizov commented on DatabasePG.go
>  	}
да так в 100 раз удобнее

2021-06-27 19:12 UTC, artur-faizov commented on DatabasePG.go
> +		historyCopyElement := historyCopyElement{
переименовал. Больше так не буду :)

2021-06-27 19:21 UTC, artur-faizov commented on DatabasePG.go
> +		err = requests.Scan(&id, &url, &method, &body, &requestTime, &respStatus, &length)
Так как у нас уже есть структура в которую мы стремимся заполнить данные то я сделал считывание напрямую в эту структуру

2021-07-02 15:20 UTC, ahamtat requested changes
Да, уже гораздо лучше. Но, можно сделать еще оптимальней.

2021-07-02 15:20 UTC, ahamtat commented on DatabasePG.go
> +		LIMIT $1 OFFSET $2
Ага, именно это я и имел в виду)

2021-07-02 15:20 UTC, ahamtat commented on DatabasePG.go
> +		err = requests.Scan(
Здесь надо сделать чтение в один параметр:
`err = requests.Scan(&elementFromTable)`

2021-07-02 15:20 UTC, ahamtat commented on DatabasePG.go
> +		historyCopy = append(historyCopy, elementFromTable)
Здесь тоже можно оптимизировать - прочитать записи из БД сразу в слайс структур.

2021-07-04 16:46 UTC, artur-faizov commented on DatabasePG.go
> +		err = requests.Scan(
в таком случае SQL выдает ошибку:
sql: expected 7 destination arguments in Scan, not 1

2021-07-04 17:16 UTC, artur-faizov commented on DatabasePG.go
> +		historyCopy = append(historyCopy, elementFromTable)
Когда начал реализовывать это улучшение понял что основная проблема для меня это то что я не знаю размер Слайса. Вроде как надо точно знать размер слайса чтобы он уже был на момент вычитки в него.
Вижу несколько путей решения проблемы:
1) Задавать размер равным Limit (параметр запроса). Но тут придется вводить функцию отсекания пустого конца у результата для случаев когда лимит не задан или когда результатов меньше чем лимит
А честно говоря городить огород с такой функцией кажется не очень оптимальным путем
2) Можно посчитать количество срок в результате а потом инициализировать слайс. Но тут проблема в том что когда я прохожусь по строкам для их подсчета функцией Next то второй раз пройтись по тем же результатам для считывания функция NEXT уже не дает. Тоесть пройтись по результатам получается можно только один раз либо для считывания данных либо для подсчета строк. А перезапрашивать у базы еще раз. - имеем риск получить несостыковку данных. СТрок может быть уже больше или меньше чем при подсчете строк до этого.

Как лучше поступить в этом случае?

2021-07-05 08:16 UTC, ahamtat commented on DatabasePG.go
> +		err = requests.Scan(
Можешь в комментарии проиллюстрировать куском кода? Немного не понимаю, как выглядит твой запрос и вызов скана?

2021-07-05 08:32 UTC, ahamtat commented on DatabasePG.go
> +		historyCopy = append(historyCopy, elementFromTable)
Можно воспользоваться встроенными функциями из пакета расширения sqlx. Например, вот этими: https://jmoiron.github.io/sqlx/#altScanning

2021-07-10 18:45 UTC, artur-faizov commented on DatabasePG.go
> +		err = requests.Scan(
Запрос в базу
`requests, err := db2.Queryx(`
		SELECT * FROM requests 
		ORDER by time ASC
		LIMIT $1 OFFSET $2
	`, limit, offset)`
Вызов скана
`err = requests.Scan(
				&historyCopy[elementNumberInSlice].ID,
				&historyCopy[elementNumberInSlice].Element.Request.Url,
				&historyCopy[elementNumberInSlice].Element.Request.Method,
				&historyCopy[elementNumberInSlice].Element.Request.Body,
				&historyCopy[elementNumberInSlice].Element.Time,
				&historyCopy[elementNumberInSlice].Element.Respond.HttpStatusCode,
				&historyCopy[elementNumberInSlice].Element.Respond.ContentLength,
			)`
В описании пакета sqlx есть сканирование сразу в структуру (StructScan) но проблема в том что он сканирует в структуру одного уровня. А у меня структура которая содержит в себе еще две структуры 
`type HistoryElement struct {
	Request Request
	Respond Respond
	Time    time.Time
}

type Request struct {
	Method string              `json:"method"`
	Url    string              `json:"url"`
	Header map[string][]string `json:"header"`
	Body   string              `json:"body"`
}

type Respond struct {
	HttpStatusCode int
	Header         http.Header
	ContentLength  int
}`
и данные надо записывать на все уровни структур, как в родительсую так и в дочерние. Предлагаю оставить как есть. Не вижу проблем иметь прямоу заполнение в финальную структуру через указатели на конкретные эелементы.

2021-07-10 18:50 UTC, artur-faizov commented on DatabasePG.go
> +		historyCopy = append(historyCopy, elementFromTable)
Поизучал sqlx и методы скана что он предлагает. Проблема в том что сканирование в слайс или мапу выдает соответственно слайс и мапу для одной строки из результата запроса. А мне нужно было посчитать количество строк. Тоесть данные методы проблему не решают. В итоге реализовал два запроса в базу.
Первый запрос спрашивает сколько там строк
Второй получает сами данные.
На основе первого запроса создаю срез финальных результатов и считываю данные прямо в финальный срез
Есть небольшой риск того что между двумя запросами в базу данные изменятся и мы получим либо больше либо меньше результатов чем ожидаем. Если результатов будет меньше (например кутото удалил из истории запрос) то в ответе последний эелемент будет просто пустой. А если запросов будет больше то новые избыточные элементы я не выведу в результат.

2021-07-12 09:11 UTC, ahamtat requested changes
Пока не получилось сканирование таблицы в слайс структур. Попробуй еще варианты.

2021-07-12 09:11 UTC, ahamtat commented on DatabasePG.go
> +	}
Коннект лучше вынести в отдельную функцию, которая запускается при инициализации PgDB. Иначе будут утекать коннекты к БД, количество которых конечно.

2021-07-12 09:11 UTC, ahamtat commented on DatabasePG.go
> +	numberOfRequests.Scan(&rowsNumber)
Запрос на количество строк в БД лишний. Нужно просто получить строки из таблицы и работать с ними как со слайсом структур. Соответственно, у слайса всегда можно узнать длину функцией len()

2021-07-12 09:11 UTC, ahamtat commented on DatabasePG.go
> +	historyCopy := make([]*historyCopyElement, rowsNumber)
А эта строка компилируется?

2021-07-12 09:11 UTC, ahamtat commented on DatabasePG.go
> +		if elementNumberInSlice <= rowsNumber {
Смысл этого условия не могу понять. Зачем нужна эта проверка?

2021-07-12 09:11 UTC, ahamtat commented on DatabasePG.go
> +				&historyCopy[elementNumberInSlice].Element.Respond.ContentLength,
Здесь опять чтение в поля структуры. Я в прошлом ПРе писал про функции, которые сканируют прямо в слайс структур через рефлексию.

2021-07-12 09:23 UTC, ahamtat commented on DatabasePG.go
> +		historyCopy = append(historyCopy, elementFromTable)
Не понимаю, в чем необходимость считать количество строк?

2021-07-12 09:27 UTC, ahamtat commented on DatabasePG.go
> +		err = requests.Scan(
В этом случае можно читать в слайс промежуточных структур, а потом заполняют из них слайс historyCopy. Необходимо, чтобы ты потренировал различные варианты работы с запросами. В продакшн-коде мы оптимизируем SQL-запросы и они сразу возвращают слайс из структур.

2021-07-26 17:05 UTC, ahamtat requested changes
Отлично. Получилось очень лаконично и по-взрослому) Пожалуйста, исправь по моим комментам и я заапрувлю.

2021-07-26 17:05 UTC, ahamtat commented on DatabasePG.go
> +	port     = ":5432"
Обычно это поле называют, наоборот, host или address)

2021-07-26 17:05 UTC, ahamtat commented on DatabasePG.go
> +	Length int
Без тегов работают запросы в БД?

2021-07-26 17:05 UTC, ahamtat commented on DatabasePG.go
> +		Select()
Ага, вот примерно это и хотелось увидеть.

2021-07-26 17:05 UTC, ahamtat commented on DatabasePG.go
> +	var requests []RequestInDB
Совсем круто было бы вот так:
`var requests []*RequestInDB`

2021-07-26 17:05 UTC, ahamtat commented on DatabasePG.go
> +		historyCopy[i].Element.Respond.ContentLength = requests[i].Length
Более гошный стиль - цикл через range и добавление элементов в массив через append. Хотя, если много элеменов в таблице, то твой вариант будет оптимальней.

2021-07-26 17:30 UTC, artur-faizov commented on DatabasePG.go
> +	Length int
функционал отрабатывает, поверял все типы запросов как на добавление данных так и на считывание

2021-07-26 17:38 UTC, artur-faizov commented on DatabasePG.go
> +	var requests []RequestInDB
Офигеть! как это работает??!! оно работает но я не понимаю как??
тоесть я могу создать хоть срез структур хоть срез ссылок на структуры и функция сама заполнит срез тем типом данных какой требуется!!! Это какой то общий механизм или так супер круто сделан Select в go-pg?

2021-07-26 18:14 UTC, artur-faizov commented on DatabasePG.go
> +		historyCopy[i].Element.Respond.ContentLength = requests[i].Length
переделал на append
вот тут пишут что в новых версиях golang разницы между прямым присвоением и аппендом почти нет
https://stackoverflow.com/questions/38654729/golang-slice-append-vs-assign-performance

2021-07-26 18:55 UTC, ahamtat approved these changes

2021-07-28 16:43 UTC, merged